name: Build Node binaries for Windows

on:
  workflow_dispatch:
  workflow_call:

jobs:
  windows:
    runs-on: ${{ matrix.arch.os }}
    name: windows-${{ matrix.arch.name }} (${{ matrix.target-node }})

    strategy:
      fail-fast: false
      matrix:
        target-node: [20, 22, 24]
        arch:
          - name: x64
            os: windows-2022
          - name: arm64
            os: windows-11-arm

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          check-latest: true

      - run: yarn install --ignore-engines

      - run: choco install nasm

      - run: yarn start --node-range node${{ matrix.target-node }} --arch ${{ matrix.arch.name }} --output dist

      - name: Check if binary is compiled, skip if download only
        id: check_file
        run: |
          ls dist
          if (Test-Path -Path dist\\*.sha256sum -PathType Leaf) { 
            "EXISTS=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else { 
            "EXISTS=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }

      - uses: actions/upload-artifact@v4
        if: steps.check_file.outputs.EXISTS == 'true'
        with:
          name: node${{ matrix.target-node }}-windows-${{ matrix.arch.name }}
          path: dist\\*
